# Generated by Django 2.1.7 on 2019-05-30 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0001_initial'),
        ('posts', '0002_auto_20190521_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='favorites',
            field=models.ManyToManyField(related_name='favorites', to='favorites.Favorite'),
        ),
    ]
