# Generated by Django 2.1.7 on 2019-03-19 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('users', '0004_profile_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='joined_groups',
            field=models.ManyToManyField(related_name='joined_groups', to='groups.Group'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='groups',
            field=models.ManyToManyField(related_name='my_groups', to='groups.Group'),
        ),
    ]
