# Generated by Django 2.1.7 on 2019-05-21 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        ('users', '0005_auto_20190319_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='posts',
            field=models.ManyToManyField(related_name='my_posts', to='posts.Post'),
        ),
    ]
