# Generated by Django 2.1.7 on 2019-05-30 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_favorites'),
        ('users', '0006_profile_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorites',
            field=models.ManyToManyField(related_name='favorited_posts', to='posts.Post'),
        ),
    ]
