# Generated by Django 2.1.7 on 2019-07-12 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='favorites',
        ),
    ]
