# Generated by Django 2.1.7 on 2019-06-05 20:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
