# Generated by Django 2.1.7 on 2019-03-17 09:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_profile_friends'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('u_id', models.CharField(default=0, max_length=8)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='users.Profile')),
                ('members', models.ManyToManyField(related_name='member', to='users.Profile')),
            ],
        ),
    ]
