# Generated by Django 2.1.7 on 2019-05-21 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='posts',
            field=models.ManyToManyField(related_name='group_posts', to='posts.Post'),
        ),
    ]
